In [1]:
import numpy as np
import mne
import pyxdf
from mnelab.io import read_raw

import fbcca

<frozen importlib._bootstrap>:241: FutureWarning: mne.io.pick.channel_type is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:241: FutureWarning: mne.io.pick.channel_type is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:241: FutureWarning: mne.io.pick.get_channel_type_constants is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:241: FutureWarning: mne.io.pick.get_channel_type_constants is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:241: FutureWarning: mne.io.pick.get_channel_type_constants is deprecated w

In [93]:
path = "/Users/alkalisk/Downloads/Recording/"
fname = path + "1207/sub-tsun_ses-1207_task-Default_run-001_eeg.xdf"
streams, header = pyxdf.load_xdf(fname)
for i in streams:
    if i['info']['name'][0] == 'obci_eeg1':
        eeg_id = i['info']['stream_id']
    print(i['info']['name'][0])
    print('stream_id: ' + str(i['info']['stream_id']))
    print('---')
print('use eeg id is ' + str(eeg_id))

Stream 1: Calculated effective sampling rate 95.6888 Hz is different from specified rate 125.0000 Hz.


MotorImag-Markers
stream_id: 3
---
obci_eeg3
stream_id: 1
---
obci_eeg1
stream_id: 4
---
obci_eeg2
stream_id: 2
---
use eeg id is 4


In [94]:
raw_ori = read_raw(fname, stream_ids=[eeg_id], fs_new=125)
raw_ori.set_channel_types({'obci_eeg1_0':'eeg','obci_eeg1_1':'eeg','obci_eeg1_2':'eeg','obci_eeg1_3':'eeg',
                       'obci_eeg1_4':'eeg','obci_eeg1_5':'eeg','obci_eeg1_6':'eeg','obci_eeg1_7':'eeg',
                       'obci_eeg1_8':'eeg','obci_eeg1_9':'eeg','obci_eeg1_10':'eeg','obci_eeg1_11':'eeg',
                       'obci_eeg1_12':'eeg','obci_eeg1_13':'eeg','obci_eeg1_14':'eeg','obci_eeg1_15':'eeg'
                     })
'''
#for old recording
raw_ori.rename_channels({'obci_eeg1_0':'Fp1','obci_eeg1_1':'Fp2','obci_eeg1_2':'C3','obci_eeg1_3':'C4',
                     'obci_eeg1_4':'P7','obci_eeg1_5':'P8','obci_eeg1_6':'O1','obci_eeg1_7':'O2',
                     'obci_eeg1_8':'F7','obci_eeg1_9':'F8','obci_eeg1_10':'F3','obci_eeg1_11':'F4',
                     'obci_eeg1_12':'T7','obci_eeg1_13':'T8','obci_eeg1_14':'P3','obci_eeg1_15':'P4'
                     })

raw_ori.rename_channels({'obci_eeg1_0':'O1', 'obci_eeg1_1':'O2',
                         'obci_eeg1_2':'PO3','obci_eeg1_3':'PO4',
                         'obci_eeg1_4':'P3', 'obci_eeg1_5':'P4',
                         'obci_eeg1_6':'C3', 'obci_eeg1_7':'C4',
                         'obci_eeg1_8':'F3', 'obci_eeg1_9':'F4',
                         'obci_eeg1_10':'T3','obci_eeg1_11':'T4',
                         'obci_eeg1_12':'Cz','obci_eeg1_13':'Fz',
                         'obci_eeg1_14':'CP5','obci_eeg1_15':'CP6'
                         })
'''
#for data after 1207
raw_ori.rename_channels({'obci_eeg1_0':'O1', 'obci_eeg1_1':'O2',
                         'obci_eeg1_2':'PO3','obci_eeg1_3':'PO4',
                         'obci_eeg1_4':'P3', 'obci_eeg1_5':'P4',
                         'obci_eeg1_6':'C3', 'obci_eeg1_7':'C4',
                         'obci_eeg1_8':'F3', 'obci_eeg1_9':'F4',
                         'obci_eeg1_10':'T3','obci_eeg1_11':'T4',
                         'obci_eeg1_12':'Cz','obci_eeg1_13':'Pz',
                         'obci_eeg1_14':'CP1','obci_eeg1_15':'CP2'
                         })
raw_ori.reorder_channels(['O1','O2','PO3','PO4','P3','Pz','P4','CP1',
                          'CP2','T3','C3','Cz','C4','T4','F3','F4'])

raw_ori.set_montage('standard_1020')
raw = raw_ori.copy()
raw.apply_function(lambda x: x * 1e-6 /10)
raw_filter = raw.copy().filter(l_freq=1, h_freq=50)

Stream 1: Calculated effective sampling rate 95.6888 Hz is different from specified rate 125.0000 Hz.


Creating RawArray with float64 data, n_channels=16, n_times=215224
    Range : 0 ... 215223 =      0.000 ...  1721.784 secs
Ready.
Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 1 - 50 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Upper passband edge: 50.00 Hz
- Upper transition bandwidth: 12.50 Hz (-6 dB cutoff frequency: 56.25 Hz)
- Filter length: 413 samples (3.304 s)



/var/folders/k_/m6hrxyv11xlfgj_0mzzyg_sc0000gp/T/ipykernel_69345/3652734312.py:2: RuntimeWarning: The unit for channel(s) obci_eeg1_0, obci_eeg1_1, obci_eeg1_10, obci_eeg1_11, obci_eeg1_12, obci_eeg1_13, obci_eeg1_14, obci_eeg1_15, obci_eeg1_2, obci_eeg1_3, obci_eeg1_4, obci_eeg1_5, obci_eeg1_6, obci_eeg1_7, obci_eeg1_8, obci_eeg1_9 has changed from NA to V.
  raw_ori.set_channel_types({'obci_eeg1_0':'eeg','obci_eeg1_1':'eeg','obci_eeg1_2':'eeg','obci_eeg1_3':'eeg',


In [95]:
events,all_events_id=mne.events_from_annotations(raw,event_id='auto')

Used Annotations descriptions: ['BH', 'EOG-close begin', 'EOG-close end', 'EOG-close trial', 'EOG-open begin', 'EOG-open end', 'EOG-open trial', 'F', 'LH', 'RH', 'SESSION-begin', 'SSVEP', 'Warm-up trial-begin', 'Warm-up trial-end', 'Warm-up-begin', 'Warm-up-end', 'Warm-upBH', 'Warm-upF', 'Warm-upLH', 'Warm-upRH', 'Warm-upSSVEP', 'calib-begin', 'calib-end', 'trial-begin', 'trial-end']


In [96]:
for idx in ['BH', 'F', 'LH','RH', 'SSVEP']:
    print(idx + ' is ' + str(all_events_id[idx]))

BH is 1
F is 8
LH is 9
RH is 10
SSVEP is 12


In [97]:
pick_ssvep =  mne.pick_channels(raw.info["ch_names"], include=["O1", "O2", "PO3", "PO4","P3","P4","Pz","CP1","CP2"])

/var/folders/k_/m6hrxyv11xlfgj_0mzzyg_sc0000gp/T/ipykernel_69345/1338705724.py:1: FutureWarning: The default for pick_channels will change from ordered=False to ordered=True in 1.5 and this will result in a change of behavior because the resulting channel order will not match. Either use a channel order that matches your instance or pass ordered=False.
  pick_ssvep =  mne.pick_channels(raw.info["ch_names"], include=["O1", "O2", "PO3", "PO4","P3","P4","Pz","CP1","CP2"])


In [98]:
event_id = dict({'SSVEP': 12})
tmin = 1
tmax = 3
#ssvep_epochs = mne.Epochs(raw, events, event_id, 
#                          tmin, tmax,
#                          baseline=None , preload=True, event_repeated = 'drop')
ssvep_epochs = mne.Epochs(raw, events, event_id, 
                          tmin, tmax, picks = pick_ssvep,
                          baseline=None , preload=True, event_repeated = 'drop')

Not setting metadata
48 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 48 events and 251 original time points ...
0 bad epochs dropped


In [99]:
ssvep_epochs.info

Measurement date,Unknown
Experimenter,Unknown
Participant,Unknown
Digitized points,19 points
Good channels,9 EEG
Bad channels,None
EOG channels,Not available
ECG channels,Not available
Sampling frequency,125.00 Hz
Highpass,0.00 Hz
Lowpass,62.50 Hz


In [102]:
list_freqs = (6,7.5,10,15)
fs = 125
preds = []
for i in range(len(ssvep_epochs.events[:,2])):
    pred = fbcca.fbcca_realtime(ssvep_epochs.get_data(copy=True)[i], list_freqs, fs, num_harms=6, num_fbs=4)
    if pred == 0 or pred == 4:
         preds.append(1)
    else:
         preds.append(0)
print(np.mean(preds))

[1.57275528 1.46647006 0.97949753 0.86246443]
[1.65442846 1.2482665  1.29633627 1.17726426]
[1.36074563 1.20706013 1.1075887  0.98289429]
[1.68790909 0.97312704 1.31437472 0.84533273]
[1.48321922 1.30137572 1.31888939 1.07008474]
[1.616989   1.14408247 1.23485286 0.97209684]
[1.67597263 1.3213659  1.23732569 1.18162385]
[1.39905875 1.16804775 1.22850763 0.93351051]
[1.36842484 1.33042829 1.18595101 0.94219794]
[1.6605061  1.00946389 1.2713939  0.94698117]
[1.4670686  1.00780522 1.05246964 0.88363734]
[1.72209696 1.12609636 1.340595   0.92185584]
[1.46940335 1.30083434 1.08872302 0.93437706]
[1.76139231 1.40024235 1.13673681 1.15281878]
[1.85088617 1.28906441 1.33620127 0.94650776]
[1.48298803 1.26962836 1.49904683 0.89636845]
[1.73506413 1.10618841 1.17616641 0.95166865]
[1.22393328 1.12798312 1.14836783 1.05341085]
[1.68924343 1.09013425 1.17169929 1.02807199]
[1.52948882 1.18802701 1.32696848 0.88594871]
[1.87649864 1.27534537 1.19386841 1.08748931]
[1.30116878 1.38586152 1.3433216  

In [85]:
event_id = dict({'BH': 1,
                 'F': 8,
                 'LH': 9,
                 'RH': 10,
                 'SSVEP':12})
tmin = 0
tmax = 3
epochs = mne.Epochs(raw, events, event_id, 
                    tmin, tmax, picks = pick_ssvep,
                    baseline=None , preload=True, event_repeated = 'drop')


Not setting metadata
192 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 192 events and 376 original time points ...
0 bad epochs dropped


In [86]:
epochs.events[:,2]

array([ 1,  8,  1,  8,  9,  8, 10,  8, 10,  9, 10, 10,  8,  1,  8,  8, 10,
       10,  9,  1,  9,  1,  1,  1, 10,  9,  9,  9,  8,  9, 10,  1,  8, 10,
        9, 10, 10,  1, 10,  8, 10, 10,  1,  1,  9,  9, 10,  1,  1,  9,  8,
        1,  8,  8,  8,  8,  1,  9, 10,  8,  9,  9,  9,  1,  1, 10,  1,  8,
        1,  1,  9, 10, 10, 10,  8,  8,  1,  9,  9,  8, 10,  8, 10,  1,  8,
       10,  1,  9,  1,  8,  9, 10,  9,  9,  9,  8,  9,  1,  1,  8, 10,  8,
        9,  9,  9,  1,  8, 10,  8,  9, 10,  9,  1, 10,  8, 10,  1,  8,  8,
        9, 10,  9,  1,  8, 10, 10,  1,  1,  1,  8,  1, 10, 10,  8,  1,  8,
        9, 10, 10, 10,  1,  1, 10,  1,  9,  8,  9, 10,  9, 10,  8,  9,  8,
        8,  8,  1,  1,  9,  9,  9,  8, 10,  9,  1,  9,  1,  8,  8,  8,  1,
        1,  1, 10, 10,  9,  1,  9,  1,  9,  8,  8,  8, 10,  9, 10,  1,  9,
        9, 10,  8, 10, 10])

In [92]:
list_freqs = (6,7,8,9)
fs = 125
preds = []
for i in range(len(epochs.events[:,2])):
    pred = fbcca.fbcca_realtime(epochs.get_data(copy=True)[i], list_freqs, fs, num_harms=5, num_fbs=4)
    if epochs.events[:,2][0] == 12:    
        if pred == 1:
             preds.append(1)
        else:
             preds.append(0)
    else:
        if pred != 0:
             preds.append(1)
        else:
             preds.append(0)
print(np.mean(preds))

[1.21708424 0.9447779  1.14204578 0.94202148]
[1.2571647  1.01403986 1.02421598 0.8540529 ]
[1.06254891 0.81216455 0.87177737 0.87846967]
[1.06324532 1.07789553 0.8719679  0.89693355]
[0.94328359 1.00780993 0.95720708 0.80920812]
[1.16559269 1.06048072 0.95701556 0.83200673]
[1.06765562 0.99633577 0.89591562 0.83945323]
[0.99280847 0.78284391 0.98550571 0.95541399]
[1.01124075 1.05411393 1.02949909 0.79355743]
[1.2531231  1.00903475 1.15680665 0.88976772]
[1.0291443  0.97938417 0.8244402  0.80481032]
[0.95974902 1.09568226 1.02129841 1.04056485]
[1.07688023 0.97673298 1.07204486 0.9020254 ]
[1.03319525 1.02694135 0.97122445 1.0173366 ]
[0.92912678 0.98294148 0.94072058 1.00459067]
[1.00798939 0.84369764 0.99481594 0.93990716]
[0.98181165 1.0089151  0.82016905 1.01631375]
[0.8773025  1.11949746 1.02554283 0.89820256]
[0.95233192 0.84104305 0.8867349  0.99411997]
[1.10833656 1.0452146  0.90471103 0.85863102]
[1.29669833 0.96786482 1.00083148 1.06126412]
[1.09649628 1.02551309 0.91460447 